*&---------------------------------------------------------------------*
*&  Include           Y_000_FGI_F01
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&      Form  LF_COMMON_FIELDS
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*

FORM LF_COMMON_FIELDS .

  CLEAR: GT_COMMON_FIELDS.
  
  SELECT * FROM DD03L INTO TABLE GT_TAB1 WHERE TABNAME = P1.
  SELECT * FROM DD03L INTO TABLE GT_TAB2 WHERE TABNAME = P2.
  
  LOOP AT GT_TAB1 ASSIGNING FIELD-SYMBOL(<LFS_TAB1>).
  
    READ TABLE GT_TAB2 WITH KEY FIELDNAME = <LFS_TAB1>-FIELDNAME ASSIGNING FIELD-SYMBOL(<LFS_TAB2>) BINARY SEARCH.
  
    IF SY-SUBRC = 0 AND <LFS_TAB1>-ROLLNAME IS NOT INITIAL AND <LFS_TAB1>-DOMNAME <> 'XFELD' AND <LFS_TAB1>-DOMNAME IS NOT INITIAL.
  
      GS_COMMON_FIELDS-COMMON    = 'FIELDNAME'.
      GS_COMMON_FIELDS-TABNAME   = <LFS_TAB1>-TABNAME.
      GS_COMMON_FIELDS-KEYFLAG   = <LFS_TAB1>-KEYFLAG.
      GS_COMMON_FIELDS-FIELDNAME = <LFS_TAB1>-FIELDNAME.
      GS_COMMON_FIELDS-ROLLNAME  = <LFS_TAB1>-ROLLNAME.
      GS_COMMON_FIELDS-DOMNAME   = <LFS_TAB1>-DOMNAME.
      GS_COMMON_FIELDS-DATATYPE  = <LFS_TAB1>-DATATYPE.
      GS_COMMON_FIELDS-LENG      = <LFS_TAB1>-LENG.
  
      APPEND GS_COMMON_FIELDS TO GT_COMMON_FIELDS.
      CLEAR: GS_COMMON_FIELDS.
  
      GS_COMMON_FIELDS-COMMON    = 'FIELDNAME'.
      GS_COMMON_FIELDS-TABNAME   = <LFS_TAB2>-TABNAME.
      GS_COMMON_FIELDS-KEYFLAG   = <LFS_TAB2>-KEYFLAG.
      GS_COMMON_FIELDS-FIELDNAME = <LFS_TAB2>-FIELDNAME.
      GS_COMMON_FIELDS-ROLLNAME  = <LFS_TAB2>-ROLLNAME.
      GS_COMMON_FIELDS-DOMNAME   = <LFS_TAB2>-DOMNAME.
      GS_COMMON_FIELDS-DATATYPE  = <LFS_TAB2>-DATATYPE.
      GS_COMMON_FIELDS-LENG      = <LFS_TAB2>-LENG.
  
      APPEND GS_COMMON_FIELDS TO GT_COMMON_FIELDS.
      CLEAR: GS_COMMON_FIELDS.
  
      CONTINUE.
    ENDIF.
  
    READ TABLE GT_TAB2 WITH KEY ROLLNAME = <LFS_TAB1>-ROLLNAME ASSIGNING FIELD-SYMBOL(<LFS_TAB3>) BINARY SEARCH.
  
    IF SY-SUBRC = 0 AND <LFS_TAB1>-ROLLNAME IS NOT INITIAL AND <LFS_TAB1>-DOMNAME <> 'XFELD' AND <LFS_TAB1>-DOMNAME IS NOT INITIAL.
  
      GS_COMMON_FIELDS-COMMON    = 'DATA_ELEMENT'.
      GS_COMMON_FIELDS-TABNAME   = <LFS_TAB1>-TABNAME.
      GS_COMMON_FIELDS-KEYFLAG   = <LFS_TAB1>-KEYFLAG.
      GS_COMMON_FIELDS-FIELDNAME = <LFS_TAB1>-FIELDNAME.
      GS_COMMON_FIELDS-ROLLNAME  = <LFS_TAB1>-ROLLNAME.
      GS_COMMON_FIELDS-DOMNAME   = <LFS_TAB1>-DOMNAME.
      GS_COMMON_FIELDS-DATATYPE  = <LFS_TAB1>-DATATYPE.
      GS_COMMON_FIELDS-LENG      = <LFS_TAB1>-LENG.
  
      APPEND GS_COMMON_FIELDS TO GT_COMMON_FIELDS.
      CLEAR: GS_COMMON_FIELDS.
  
      GS_COMMON_FIELDS-COMMON    = 'DATA_ELEMENT'.
      GS_COMMON_FIELDS-TABNAME   = <LFS_TAB3>-TABNAME.
      GS_COMMON_FIELDS-KEYFLAG   = <LFS_TAB3>-KEYFLAG.
      GS_COMMON_FIELDS-FIELDNAME = <LFS_TAB3>-FIELDNAME.
      GS_COMMON_FIELDS-ROLLNAME  = <LFS_TAB3>-ROLLNAME.
      GS_COMMON_FIELDS-DOMNAME   = <LFS_TAB3>-DOMNAME.
      GS_COMMON_FIELDS-DATATYPE  = <LFS_TAB3>-DATATYPE.
      GS_COMMON_FIELDS-LENG      = <LFS_TAB3>-LENG.
  
      APPEND GS_COMMON_FIELDS TO GT_COMMON_FIELDS.
      CLEAR: GS_COMMON_FIELDS.
  
      CONTINUE.
    ENDIF.
  
    READ TABLE GT_TAB2 WITH KEY DOMNAME = <LFS_TAB1>-DOMNAME ASSIGNING FIELD-SYMBOL(<LFS_TAB4>) BINARY SEARCH.
  
    IF SY-SUBRC = 0 AND <LFS_TAB1>-ROLLNAME IS NOT INITIAL AND <LFS_TAB1>-DOMNAME <> 'XFELD' AND <LFS_TAB1>-DOMNAME IS NOT INITIAL.
  
      GS_COMMON_FIELDS-COMMON    = 'DOMAIN_NAME'.
      GS_COMMON_FIELDS-TABNAME   = <LFS_TAB1>-TABNAME.
      GS_COMMON_FIELDS-KEYFLAG   = <LFS_TAB1>-KEYFLAG.
      GS_COMMON_FIELDS-FIELDNAME = <LFS_TAB1>-FIELDNAME.
      GS_COMMON_FIELDS-ROLLNAME  = <LFS_TAB1>-ROLLNAME.
      GS_COMMON_FIELDS-DOMNAME   = <LFS_TAB1>-DOMNAME.
      GS_COMMON_FIELDS-DATATYPE  = <LFS_TAB1>-DATATYPE.
      GS_COMMON_FIELDS-LENG      = <LFS_TAB1>-LENG.
  
      APPEND GS_COMMON_FIELDS TO GT_COMMON_FIELDS.
      CLEAR: GS_COMMON_FIELDS.
  
      GS_COMMON_FIELDS-COMMON    = 'DOMAIN_NAME'.
      GS_COMMON_FIELDS-TABNAME   = <LFS_TAB4>-TABNAME.
      GS_COMMON_FIELDS-KEYFLAG   = <LFS_TAB4>-KEYFLAG.
      GS_COMMON_FIELDS-FIELDNAME = <LFS_TAB4>-FIELDNAME.
      GS_COMMON_FIELDS-ROLLNAME  = <LFS_TAB4>-ROLLNAME.
      GS_COMMON_FIELDS-DOMNAME   = <LFS_TAB4>-DOMNAME.
      GS_COMMON_FIELDS-DATATYPE  = <LFS_TAB4>-DATATYPE.
      GS_COMMON_FIELDS-LENG      = <LFS_TAB4>-LENG.
  
      APPEND GS_COMMON_FIELDS TO GT_COMMON_FIELDS.
      CLEAR: GS_COMMON_FIELDS.
  
      CONTINUE.
    ENDIF.
  
  ENDLOOP.
  
  IF GT_COMMON_FIELDS[] IS INITIAL.
    MESSAGE 'NO COMMON FIELDS BETWEEN' && ' ' && P1 && ' ' && 'AND' && ' ' && P2 TYPE 'I' DISPLAY LIKE 'E'.
    LEAVE PROGRAM.
*  ELSE.
*    CALL SCREEN 0110.
  ENDIF.
  
ENDFORM.

*&---------------------------------------------------------------------*
*&      Module  STATUS_0110  OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*

MODULE STATUS_0110 OUTPUT.
  SET PF-STATUS 'STATUS_0110'.
*  SET TITLEBAR 'xxx'.
  
  VARIANT-REPORT = SY-REPID.
  VARIANT-USERNAME = SY-UNAME.
  
  CLEAR: GT_FIELDCAT.
  REFRESH: GT_FIELDCAT.
  
  GS_FIELDCAT-COL_POS   = 1.
  GS_FIELDCAT-FIELDNAME = 'COMMON'.
  GS_FIELDCAT-TABNAME   = 'GT_COMMON_FIELDS'.
  GS_FIELDCAT-SCRTEXT_M = 'COMMON FIELDS'.
  GS_FIELDCAT-EMPHASIZE = 'C410'.
  GS_FIELDCAT-OUTPUTLEN = 20.
  
  APPEND GS_FIELDCAT TO GT_FIELDCAT.
  CLEAR: GS_FIELDCAT.
  
  GS_FIELDCAT-COL_POS   = 2.
  GS_FIELDCAT-FIELDNAME = 'TABNAME'.
  GS_FIELDCAT-TABNAME   = 'GT_COMMON_FIELDS'.
  GS_FIELDCAT-SCRTEXT_M = 'DB TABLE'.
  GS_FIELDCAT-EMPHASIZE = 'C430'.
  GS_FIELDCAT-OUTPUTLEN = 14.

  APPEND GS_FIELDCAT TO GT_FIELDCAT.
  CLEAR: GS_FIELDCAT.
  
  GS_FIELDCAT-COL_POS   = 3.
  GS_FIELDCAT-FIELDNAME = 'FIELDNAME'.
  GS_FIELDCAT-TABNAME   = 'GT_COMMON_FIELDS'.
  GS_FIELDCAT-SCRTEXT_M = 'FIELDNAME'.
  GS_FIELDCAT-EMPHASIZE = 'C430'.
  GS_FIELDCAT-OUTPUTLEN = 14.

  APPEND GS_FIELDCAT TO GT_FIELDCAT.
  CLEAR: GS_FIELDCAT.
  
  GS_FIELDCAT-COL_POS   = 4.
  GS_FIELDCAT-FIELDNAME = 'ROLLNAME'.
  GS_FIELDCAT-TABNAME   = 'GT_COMMON_FIELDS'.
  GS_FIELDCAT-SCRTEXT_M = 'DATA ELEMENT'.
  GS_FIELDCAT-EMPHASIZE = 'C430'.
  GS_FIELDCAT-OUTPUTLEN = 14.

  APPEND GS_FIELDCAT TO GT_FIELDCAT.
  CLEAR: GS_FIELDCAT.
  
  GS_FIELDCAT-COL_POS   = 5.
  GS_FIELDCAT-FIELDNAME = 'DOMNAME'.
  GS_FIELDCAT-TABNAME   = 'GT_COMMON_FIELDS'.
  GS_FIELDCAT-SCRTEXT_M = 'DOMAIN NAME'.
  GS_FIELDCAT-EMPHASIZE = 'C430'.
  GS_FIELDCAT-OUTPUTLEN = 14.

  APPEND GS_FIELDCAT TO GT_FIELDCAT.
  CLEAR: GS_FIELDCAT.
  
  GS_FIELDCAT-COL_POS   = 6.
  GS_FIELDCAT-FIELDNAME = 'DATATYPE'.
  GS_FIELDCAT-TABNAME   = 'GT_COMMON_FIELDS'.
  GS_FIELDCAT-SCRTEXT_M = 'DATATYPE'.
  GS_FIELDCAT-EMPHASIZE = 'C430'.
  GS_FIELDCAT-OUTPUTLEN = 9.

  APPEND GS_FIELDCAT TO GT_FIELDCAT.
  CLEAR: GS_FIELDCAT.
  
  GS_FIELDCAT-COL_POS   = 7.
  GS_FIELDCAT-FIELDNAME = 'LENG'.
  GS_FIELDCAT-TABNAME   = 'GT_COMMON_FIELDS'.
  GS_FIELDCAT-SCRTEXT_M = 'LENGTH'.
  GS_FIELDCAT-EMPHASIZE = 'C430'.
  GS_FIELDCAT-OUTPUTLEN = 8.

  APPEND GS_FIELDCAT TO GT_FIELDCAT.
  CLEAR: GS_FIELDCAT.
  
  GS_FIELDCAT-COL_POS   = 8.
  GS_FIELDCAT-FIELDNAME = 'KEYFLAG'.
  GS_FIELDCAT-TABNAME   = 'GT_COMMON_FIELDS'.
  GS_FIELDCAT-SCRTEXT_M = 'KEY'.
  GS_FIELDCAT-EMPHASIZE = 'C430'.
  GS_FIELDCAT-OUTPUTLEN = 4.

  APPEND GS_FIELDCAT TO GT_FIELDCAT.
  CLEAR: GS_FIELDCAT.
  
  CREATE OBJECT ALV_CONTAINER_JOIN_1
    EXPORTING
      CONTAINER_NAME = 'CONTAINER_JOIN_1'.
  
  CREATE OBJECT ALV_GRID_JOIN_1
    EXPORTING
      I_PARENT = ALV_CONTAINER_JOIN_1.
    
  CALL METHOD ALV_GRID_JOIN_1->SET_TABLE_FOR_FIRST_DISPLAY
    EXPORTING
      IS_LAYOUT       = LAYOUT
      IS_VARIANT      = VARIANT
      I_SAVE          = 'U'
    CHANGING
      IT_OUTTAB       = GT_COMMON_FIELDS[]
      IT_FIELDCATALOG = GT_FIELDCAT[].
  
ENDMODULE.

*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_0110  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*

MODULE USER_COMMAND_0110 INPUT.
  
  CASE SY-UCOMM.
    WHEN 'BACK'.
      LEAVE TO SCREEN 0.
    WHEN 'CANCEL'.
      LEAVE TO SCREEN 0.
    WHEN 'EXIT'.
      LEAVE PROGRAM.
    WHEN OTHERS.
  ENDCASE.
  
ENDMODULE.