*&---------------------------------------------------------------------*
*&  Include           Y_007_FGI_TOP
*&---------------------------------------------------------------------*

" PERFORM DATA_RETRIEVAL

TABLES: VBAK, VBAP, VBEP.

TYPES: BEGIN OF TY_DATA,
         VBELN TYPE VBEP-VBELN, " Sales Document
         POSNR TYPE VBEP-POSNR, " Sales Document Item
         ETENR TYPE VBEP-ETENR, " Delivery Schedule Line Number
         EDATU TYPE VBEP-EDATU, " Schedule line date
         TDDAT TYPE VBEP-TDDAT, " Transportation Planning Date
         MBDAT TYPE VBEP-MBDAT, " Material Staging/Availability Date
         LDDAT TYPE VBEP-LDDAT, " Loading Date
         WADAT TYPE VBEP-WADAT, " Goods Issue Date
       END OF TY_DATA.

DATA: GT_DATA   TYPE TABLE OF TY_DATA,
      GT_BACKUP TYPE SORTED TABLE OF TY_DATA WITH NON-UNIQUE KEY VBELN POSNR ETENR EDATU.

" PERFORM DATA_DISPLAYING

DATA: ALV_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      REF_GRID      TYPE REF TO CL_GUI_ALV_GRID,

      GT_FIELDCAT   TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE,
      GS_FIELDCAT   TYPE SLIS_FIELDCAT_ALV,

      GD_LAYOUT     TYPE SLIS_LAYOUT_ALV,

      GV_REPID      LIKE SY-REPID,

      RT_EXTAB      TYPE SLIS_T_EXTAB,
      RS_SELFIELD   TYPE SLIS_SELFIELD,

      R_UCOMM       LIKE SY-UCOMM,
      GO_MESSAGE    TYPE REF TO CX_SALV_MSG.

" PERFORM DATA_PROCESSING

DATA: GT_RETURN           TYPE STANDARD TABLE OF BAPIRET2,
      GS_RETURN           LIKE BAPIRET2,

      GS_ORDER_HEADER_IN  LIKE BAPISDH1,
      GS_ORDER_HEADER_INX LIKE BAPISDH1X,

      GT_ORDER_ITEMS_IN   TYPE TABLE OF BAPISDITM,
      GS_ORDER_ITEMS_IN   TYPE BAPISDITM,

      GT_ORDER_ITEMS_INX  TYPE TABLE OF BAPISDITMX,
      GS_ORDER_ITEMS_INX  TYPE BAPISDITMX,

      GT_ORDER_KEYS       TYPE TABLE OF BAPISDKEY,
      GS_ORDER_KEYS       LIKE BAPISDKEY,

      GT_SCHEDULE_LINES   TYPE TABLE OF BAPISCHDL WITH HEADER LINE,
      GS_SCHEDULE_LINES   LIKE BAPISCHDL,

      GT_SCHEDULE_LINESX  TYPE TABLE OF BAPISCHDLX WITH HEADER LINE,
      GS_SCHEDULE_LINESX  LIKE BAPISCHDLX.